version: '3.8'
#project_name: ''

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
